name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: mumbai
    - name: Install AWS CLI
      run: |
        sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade --user

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://ajay-portfolio-app --delete
